package methods;

import org.rspeer.runetek.api.Varps;
import org.rspeer.runetek.api.commons.BankLocation;
import org.rspeer.runetek.api.movement.position.Position;
import task_structure.TreeScript;
import task_structure.TreeTask;
import tasks.*;
import utils.AbyssEquipment;
import utils.FoodTypes;
import utils.RuneTypes;

public class Abyss extends CraftMethod {
    public Abyss(final TreeScript handler, final RuneTypes runeType, final AbyssEquipment equipment) {
        super(runeType.getId());
        final int miniquestCompleted = Varps.get(491);  //1073799168?
        handler.addNotedPosition("edgeville", new Position(3088, 3502));
        handler.addNotedPosition("mage", new Position(3107, 3557));
        handler.addNotedPosition("center abyss", new Position(3037, 4830));
        handler.addNotedPosition("outer ffa", new Position(3352, 3164));
        handler.addNotedPosition("inner ffa", new Position(3327, 4751));
        handler.addNotedPosition("clan wars", new Position(3369, 3170));
        handler.addNotedPosition("inside altar", runeType.getAltarPosition());
        final TreeTask head = new HasRunes();
        TreeTask second = head.setLeft(new HasPureEssence());
        TreeTask third = second.setLeft(new IsInAltar(handler));
        TreeTask fourth = third.setLeft(new IsBankOpen());
        TreeTask fifth = fourth.setLeft(new IsNearBank());
        TreeTask sixth = fifth.setLeft(new IsNearClanWars(handler));
        TreeTask seventh = sixth.setLeft(new IsRingEquipped());
        seventh.setLeft(new WalkToBank());
        seventh.setRight(new TeleportToClanWars(handler));
        sixth.setRight(new WalkToBank(BankLocation.CLAN_WARS));
        fifth.setRight(new OpenBank());
        fifth = fourth.setRight(new ArePouchesInInventory(handler));
        fifth.setLeft(new WithdrawPouches(handler));
        sixth = fifth.setRight(new IsWearingAbyssEquipment(equipment));
        seventh = sixth.setLeft(new IsAbyssEquipmentInInventory(equipment));
        seventh.setLeft(new WithdrawAbyssEquipment(equipment));
        seventh.setRight(new WearAbyssEquipment(equipment));
        seventh = sixth.setRight(new IsRingEquipped());
        TreeTask eighth = seventh.setLeft(new IsRingInInventory());
        eighth.setLeft(new WithdrawRing());
        eighth.setRight(new EquipRing());
        eighth = sixth.setRight(new IsGloryEquipped());
        TreeTask ninth = eighth.setLeft(new IsGloryInInventory());
        ninth.setLeft(new WithdrawGlory());
        ninth.setRight(new EquipGlory());
        ninth = eighth.setRight(new IsBadGloryInInventory());
        ninth.setLeft(new WithdrawPureEssence());
        ninth.setRight(new DepositBadGlory());
        fourth = third.setRight(new DoPouchesNeedFilling(handler));
        fourth.setLeft(new EmptyPouches(handler));
        fourth.setRight(new TeleportToClanWars(handler));
        third = second.setRight(new IsInAltar(handler));
        fourth = third.setLeft(new IsBankOpen());
        fifth = fourth.setLeft(new DoPouchesNeedFilling(handler));
        sixth = fifth.setLeft(new IsInAbyss(handler));
        seventh = sixth.setLeft(new IsNearEdgeville(handler));
        eighth = seventh.setLeft(new IsInFFA(handler));
        ninth = eighth.setLeft(new IsNearClanWars(handler));
        ninth.setLeft(new TeleportToClanWars(handler));
        TreeTask tenth = ninth.setRight(new IsBeingHunted(handler));
        TreeTask eleventh = tenth.setLeft(new HasNecessaryAbyssItems(handler));
        eleventh.setLeft(new OpenBank());
        eleventh.setRight(new UseClanWarsPortal(handler));
        tenth.setRight(new HopToFreshWorld(handler));
        eighth.setRight(new TeleportToEdgeville(handler));
        eighth = seventh.setRight(new IsNearMage());
        ninth = eighth.setLeft(new IsBeingHunted(handler));
        ninth.setLeft(new WalkToMage(handler));
        ninth.setRight(new TeleportToClanWars(handler));
        eighth.setRight(new TeleportToAbyss(handler));
        seventh = sixth.setRight(new IsInInnerAbyss());
        eighth = seventh.setLeft(new IsHealthBelowThreshold());
        eighth.setLeft(new TraverseObstacle(handler));
        eighth.setRight(new TeleportToClanWars(handler));
        eighth = seventh.setRight(new DoPouchesNeedRepairing(handler));
        eighth.setLeft(new EnterRift(handler, runeType.toString()));
        eighth.setRight(new RepairPouches());
        fifth.setRight(new FillPouches(handler));
        fifth = fourth.setRight(new IsBadGloryInInventory());
        sixth = fifth.setLeft(new HasNecessaryAbyssItems(handler));
        seventh = sixth.setLeft(new HasEnoughEssence());
        eighth = seventh.setLeft(new IsRingEquipped());
        ninth = eighth.setLeft(new IsRingInInventory());
        ninth.setLeft(new WithdrawRing());
        ninth.setRight(new EquipRing());
        ninth = eighth.setRight(new IsGloryEquipped());
        tenth = ninth.setLeft(new IsGloryInInventory());
        tenth.setLeft(new WithdrawGlory());
        tenth.setRight(new EquipGlory());
        ninth.setRight(new WithdrawPureEssence());
        seventh.setRight(new DepositPureEssence());
        sixth.setRight(new CloseBank());
        fifth.setRight(new DepositBadGlory());
        third.setRight(new CraftRunes());
        second = head.setRight(new IsInAltar(handler));
        third = second.setLeft(new IsBankOpen());
        fourth = third.setLeft(new IsNearBank());
        fifth = fourth.setLeft(new IsNearClanWars(handler));
        fifth.setLeft(new TeleportToClanWars(handler));
        fifth.setRight(new WalkToBank(BankLocation.CLAN_WARS));
        fourth.setRight(new OpenBank());
        third.setRight(new DepositRunes());
        third = second.setRight(new HasPureEssence());
        fourth = third.setLeft(new AreAllPouchesEmpty(handler));
        fourth.setLeft(new EmptyPouches(handler));
        fourth.setRight(new TeleportToClanWars(handler));
        third.setRight(new CraftRunes());
        setHead(head);
    }

    public Abyss(final TreeScript handler, final RuneTypes runeType, final FoodTypes foodType, final AbyssEquipment equipment) {
        super(runeType.getId());
        handler.addNotedPosition("edgeville", new Position(3088, 3502));
        handler.addNotedPosition("mage", new Position(3107, 3557));
        handler.addNotedPosition("center abyss", new Position(3037, 4830));
        handler.addNotedPosition("inside altar", runeType.getAltarPosition());
        final TreeTask head = new HasRunes();
        TreeTask second = head.setLeft(new HasPureEssence());
        TreeTask third = second.setLeft(new IsInAltar(handler));
        TreeTask fourth = third.setLeft(new IsBankOpen());
        TreeTask fifth = fourth.setLeft(new IsNearBank());
        TreeTask sixth = fifth.setLeft(new IsNearEdgeville(handler));
        TreeTask seventh = sixth.setLeft(new IsGloryEquipped());
        seventh.setLeft(new WalkToBank());
        seventh.setLeft(new TeleportToEdgeville(handler));
        sixth.setRight(new WalkToBank(BankLocation.EDGEVILLE));
        fifth.setRight(new OpenBank());
        fifth = fourth.setRight(new ArePouchesInInventory(handler));
        fifth.setLeft(new WithdrawPouches(handler));
        sixth = fifth.setRight(new IsWearingAbyssEquipment(equipment));
        seventh = sixth.setLeft(new IsAbyssEquipmentInInventory(equipment));
        seventh.setLeft(new WithdrawAbyssEquipment(equipment));
        seventh.setRight(new WearAbyssEquipment(equipment));
        seventh = sixth.setRight(new IsGloryEquipped());
        TreeTask eighth = seventh.setLeft(new IsGloryInInventory());
        eighth.setLeft(new WithdrawGlory());
        eighth.setRight(new EquipGlory());
        eighth = seventh.setRight(new IsBadGloryInInventory());
        TreeTask ninth = eighth.setLeft(new IsHealthBelowThreshold(2));
        TreeTask tenth = ninth.setLeft(new ShouldUseStaminaPotion(handler));
        TreeTask eleventh = tenth.setLeft(new HasStaminaPotionInInventory(true));
        eleventh.setLeft(new WithdrawPureEssence());
        eleventh.setRight(new DepositStaminaPotion());
        eleventh = tenth.setRight(new HasStaminaPotionInInventory());
        eleventh.setLeft(new WithdrawStaminaPotion());
        eleventh.setRight(new DrinkStaminaPotion());
        final String foodName = foodType.toString();
        tenth = ninth.setRight(new IsFoodInInventory(foodName));
        tenth.setLeft(new WithdrawFood(foodName));
        tenth.setRight(new EatFood(foodName));
        eighth.setRight(new DepositBadGlory());
        fourth = third.setRight(new DoPouchesNeedFilling(handler));
        fourth.setLeft(new EmptyPouches(handler));
        fourth.setRight(new TeleportToEdgeville(handler));
        third = second.setRight(new IsInAltar(handler));
        fourth = third.setLeft(new IsBankOpen());
        fifth = fourth.setLeft(new DoPouchesNeedFilling(handler));
        sixth = fifth.setLeft(new IsInAbyss(handler));
        seventh = sixth.setLeft(new IsBeingHunted(handler));
        eighth = seventh.setLeft(new IsNearMage());
        ninth = eighth.setLeft(new IsHealthBelowThreshold(2));
        tenth = ninth.setLeft(new HasNecessaryAbyssItems(handler));
        tenth.setLeft(new OpenBank());
        eleventh = tenth.setRight(new IsNearEdgeville(handler));
        eleventh.setLeft(new TeleportToEdgeville(handler));
        eleventh.setRight(new WalkToMage(handler));
        ninth.setRight(new OpenBank());
        eighth.setRight(new TeleportToAbyss(handler));
        eighth = seventh.setRight(new IsInWilderness());
        eighth.setLeft(new HopToFreshWorld(handler));
        eighth.setRight(new TeleportToEdgeville(handler));
        seventh = sixth.setRight(new IsInInnerAbyss());
        eighth = seventh.setLeft(new IsHealthBelowThreshold());
        eighth.setLeft(new TraverseObstacle(handler));
        eighth.setRight(new TeleportToEdgeville(handler));
        eighth = seventh.setRight(new DoPouchesNeedRepairing(handler));
        eighth.setLeft(new EnterRift(handler, runeType.toString()));
        eighth.setRight(new RepairPouches());
        fifth.setRight(new FillPouches(handler));
        fifth = fourth.setRight(new IsBadGloryInInventory());
        sixth = fifth.setLeft(new IsHealthBelowThreshold(2));
        seventh = sixth.setLeft(new HasNecessaryAbyssItems(handler));
        eighth = seventh.setLeft(new HasEnoughEssence());
        ninth = eighth.setLeft(new IsGloryEquipped());
        tenth = ninth.setLeft(new IsGloryInInventory());
        tenth.setLeft(new WithdrawGlory());
        tenth.setRight(new EquipGlory());
        ninth.setRight(new WithdrawPureEssence());
        eighth.setRight(new DepositPureEssence());
        seventh.setRight(new CloseBank());
        seventh = sixth.setRight(new IsFullOfEssence());
        eighth = seventh.setLeft(new IsFoodInInventory(foodName));
        eighth.setLeft(new WithdrawFood(foodName));
        eighth.setRight(new EatFood(foodName));
        seventh.setRight(new DepositPureEssence());
        fifth.setRight(new DepositBadGlory());
        third.setRight(new CraftRunes());
        second = head.setRight(new IsInAltar(handler));
        third = second.setLeft(new IsBankOpen());
        fourth = third.setLeft(new IsNearBank());
        fifth = fourth.setLeft(new IsNearEdgeville(handler));
        fifth.setLeft(new TeleportToEdgeville(handler));
        fifth.setRight(new WalkToBank(BankLocation.EDGEVILLE));
        fourth.setRight(new OpenBank());
        third.setRight(new DepositRunes());
        third = second.setRight(new HasPureEssence());
        fourth = third.setLeft(new AreAllPouchesEmpty(handler));
        fourth.setLeft(new EmptyPouches(handler));
        fourth.setRight(new TeleportToEdgeville(handler));
        third.setRight(new CraftRunes());
        setHead(head);
    }
}
